<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>DhcbTools.AutoCAD</RootNamespace>
    <AssemblyName>DhcbTools.AutoCAD</AssemblyName>
    <UseWPF>true</UseWPF>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DhcbTools.Core.AutoCAD\DhcbTools.Core.AutoCAD.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoCAD.NET" Version="24.*" />
  </ItemGroup>

</Project>
